#!/usr/bin/env python3
"""
Test Word Document Generation

Tests the convert_md_to_docx utility to verify:
1. Word document is generated successfully
2. Formatting matches markdown structure
3. AI-generated section markers are present
4. Track changes is enabled
5. Document metadata is set

Usage:
    python test_word_generation.py
"""

import os
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

from backend.utils.convert_md_to_docx import convert_markdown_to_docx


def create_test_markdown():
    """
    Create a sample markdown file for testing
    
    Returns:
        Path to created markdown file
    """
    test_content = """# Test Acquisition Document

## Executive Summary

This is a test document to verify Word generation functionality. The system should convert this markdown to a professional Word document with AI annotations.

**Program Name:** Test Acquisition System  
**Contract Value:** $1,000,000  
**Period of Performance:** 24 months

## Technical Requirements

The system must meet the following requirements:

- Requirement 1: Cloud-based deployment
- Requirement 2: FedRAMP Moderate compliance
- Requirement 3: 99.9% uptime SLA

### Performance Metrics

Performance will be measured using these key metrics:

1. Response time under 2 seconds
2. System availability 99.9%
3. User satisfaction score above 4.0/5.0

## Cost Breakdown

The following table shows the cost breakdown:

| Category | Hours | Rate | Total |
|----------|-------|------|-------|
| Senior Developer | 1000 | $150 | $150,000 |
| Mid Developer | 2000 | $100 | $200,000 |
| Project Manager | 500 | $175 | $87,500 |
| **Total** | **3500** | - | **$437,500** |

## Deliverables

The contractor shall provide the following deliverables:

1. **System Design Document** - Due Month 2
2. **Working Prototype** - Due Month 6
3. **Final System** - Due Month 12
4. **Training Materials** - Due Month 11

---

## References and Source Documents

This document was generated using AI automation.

*Generated by DoD Acquisition Automation System*  
*Generation Date: 2025-10-29*
"""
    
    # Create test directory
    test_dir = Path('test_word_output')
    test_dir.mkdir(exist_ok=True)
    
    # Write test markdown
    test_md_path = test_dir / 'test_document.md'
    with open(test_md_path, 'w', encoding='utf-8') as f:
        f.write(test_content)
    
    return test_md_path


def test_word_generation():
    """
    Test Word document generation functionality
    """
    print("="*80)
    print("WORD DOCUMENT GENERATION TEST")
    print("="*80)
    print()
    
    # Step 1: Create test markdown
    print("Step 1: Creating test markdown file...")
    test_md_path = create_test_markdown()
    print(f"  ✅ Created: {test_md_path}")
    print()
    
    # Step 2: Generate Word document
    print("Step 2: Converting markdown to Word document...")
    test_docx_path = test_md_path.parent / 'test_document.docx'
    
    try:
        convert_markdown_to_docx(
            str(test_md_path),
            str(test_docx_path),
            program_name="Test Acquisition System"
        )
        print(f"  ✅ Generated: {test_docx_path}")
        print()
    except Exception as e:
        print(f"  ❌ Error: {e}")
        import traceback
        traceback.print_exc()
        return False
    
    # Step 3: Verify file exists
    print("Step 3: Verifying Word document...")
    if test_docx_path.exists():
        file_size = test_docx_path.stat().st_size
        print(f"  ✅ File exists: {test_docx_path}")
        print(f"  ✅ File size: {file_size:,} bytes")
        print()
    else:
        print(f"  ❌ File not found: {test_docx_path}")
        return False
    
    # Step 4: Verify document properties (if python-docx is available)
    print("Step 4: Checking document properties...")
    try:
        from docx import Document
        doc = Document(str(test_docx_path))
        
        print(f"  ✅ Paragraphs: {len(doc.paragraphs)}")
        print(f"  ✅ Tables: {len(doc.tables)}")
        
        # Check metadata
        props = doc.core_properties
        print(f"  ✅ Author: {props.author}")
        print(f"  ✅ Title: {props.title}")
        print(f"  ✅ Subject: {props.subject}")
        print(f"  ✅ Comments: {props.comments[:50]}..." if props.comments else "  ⚠️  No comments")
        print()
        
    except Exception as e:
        print(f"  ⚠️  Could not verify document properties: {e}")
        print()
    
    # Step 5: Success summary
    print("="*80)
    print("TEST COMPLETED SUCCESSFULLY")
    print("="*80)
    print()
    print(f"✅ Word document generated: {test_docx_path}")
    print()
    print("Next steps:")
    print("1. Open the Word document in Microsoft Word")
    print("2. Verify AI-generated section markers are visible")
    print("3. Check that track changes is enabled (Review tab)")
    print("4. Verify tables, lists, and formatting are correct")
    print()
    print(f"Test output directory: {test_md_path.parent.absolute()}")
    print()
    
    return True


if __name__ == '__main__':
    try:
        success = test_word_generation()
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"\n❌ Test failed with error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

