/**
 * DocumentLifecycleTimeline Component
 * 
 * A vertical timeline visualization showing the lifecycle of a document:
 * - Upload: When the document was created
 * - Indexing: When RAG indexing completed
 * - Generation: When AI generation occurred
 * - Usage: When this document influenced other generations
 * 
 * This provides an audit trail for compliance and explainability.
 * 
 * Dependencies:
 * - lineageApi.getTimeline for fetching timeline data
 * - Shadcn UI components for styling
 * - React Query for data fetching
 * - date-fns for relative time formatting
 */

import { useQuery } from '@tanstack/react-query';
import { format, formatDistanceToNow } from 'date-fns';
import {
  CloudUpload,
  Database,
  Sparkles,
  GitBranch,
  Loader2,
  AlertCircle,
  Clock,
  User,
  FileText,
  CheckCircle2,
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import { lineageApi, type TimelineEvent, type TimelineEventType } from '@/services/api';
import { useState } from 'react';
import { ChevronDown, ChevronRight } from 'lucide-react';

// Props interface for DocumentLifecycleTimeline
interface DocumentLifecycleTimelineProps {
  documentId: string;
  documentName?: string;
  compact?: boolean;
}

// Configuration for timeline event display
const EVENT_CONFIG: Record<TimelineEventType, {
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  bgColor: string;
  borderColor: string;
  description: string;
}> = {
  uploaded: {
    label: 'Document Created',
    icon: CloudUpload,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
    borderColor: 'border-blue-300',
    description: 'Document was uploaded or created',
  },
  indexed: {
    label: 'RAG Indexed',
    icon: Database,
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-100',
    borderColor: 'border-emerald-300',
    description: 'Content was processed and indexed for retrieval',
  },
  generated: {
    label: 'AI Generated',
    icon: Sparkles,
    color: 'text-violet-600',
    bgColor: 'bg-violet-100',
    borderColor: 'border-violet-300',
    description: 'Content was generated by AI',
  },
  used_as_source: {
    label: 'Used as Source',
    icon: GitBranch,
    color: 'text-amber-600',
    bgColor: 'bg-amber-100',
    borderColor: 'border-amber-300',
    description: 'This document influenced another document',
  },
};

/**
 * TimelineEventItem - Single event in the timeline
 */
function TimelineEventItem({ 
  event, 
  isLast 
}: { 
  event: TimelineEvent; 
  isLast: boolean;
}) {
  const [isExpanded, setIsExpanded] = useState(false);
  const config = EVENT_CONFIG[event.type] || EVENT_CONFIG.uploaded;
  const Icon = config.icon;

  // Format timestamp
  const eventDate = event.timestamp ? new Date(event.timestamp) : null;
  const relativeTime = eventDate 
    ? formatDistanceToNow(eventDate, { addSuffix: true })
    : 'Unknown time';
  const absoluteTime = eventDate
    ? format(eventDate, 'MMM d, yyyy h:mm a')
    : 'Unknown';

  // Build detail items from event details
  const detailItems = Object.entries(event.details || {}).filter(
    ([, value]) => value !== null && value !== undefined
  );

  return (
    <div className="relative flex gap-4">
      {/* Timeline Line */}
      {!isLast && (
        <div className="absolute left-[19px] top-10 bottom-0 w-0.5 bg-slate-200" />
      )}

      {/* Event Icon */}
      <div
        className={`relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full ${config.bgColor} ${config.borderColor} border-2`}
      >
        <Icon className={`h-5 w-5 ${config.color}`} />
      </div>

      {/* Event Content */}
      <Collapsible 
        open={isExpanded} 
        onOpenChange={setIsExpanded}
        className="flex-1 pb-6"
      >
        <div className="flex items-start justify-between">
          <div>
            <CollapsibleTrigger className="flex items-center gap-2 hover:opacity-80 transition-opacity">
              <h4 className="font-semibold text-sm">{config.label}</h4>
              {detailItems.length > 0 && (
                isExpanded 
                  ? <ChevronDown className="h-4 w-4 text-muted-foreground" />
                  : <ChevronRight className="h-4 w-4 text-muted-foreground" />
              )}
            </CollapsibleTrigger>
            <p className="text-xs text-muted-foreground mt-0.5">
              {config.description}
            </p>
          </div>

          {/* Timestamp */}
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <div className="flex items-center gap-1 text-xs text-muted-foreground">
                  <Clock className="h-3 w-3" />
                  {relativeTime}
                </div>
              </TooltipTrigger>
              <TooltipContent>
                <p>{absoluteTime}</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>

        {/* Expandable Details */}
        {detailItems.length > 0 && (
          <CollapsibleContent>
            <div className="mt-3 p-3 rounded-lg bg-slate-50 border text-sm space-y-2">
              {detailItems.map(([key, value]) => (
                <div key={key} className="flex items-center gap-2">
                  <span className="text-muted-foreground capitalize">
                    {key.replace(/_/g, ' ')}:
                  </span>
                  <span className="font-medium">
                    {typeof value === 'number' 
                      ? value.toLocaleString() 
                      : String(value)
                    }
                  </span>
                </div>
              ))}

              {/* Actor if present */}
              {event.actor && (
                <div className="flex items-center gap-2 pt-2 border-t">
                  <User className="h-3.5 w-3.5 text-muted-foreground" />
                  <span className="text-muted-foreground">By:</span>
                  <span className="font-medium">{event.actor}</span>
                </div>
              )}
            </div>
          </CollapsibleContent>
        )}
      </Collapsible>
    </div>
  );
}

export function DocumentLifecycleTimeline({
  documentId,
  documentName,
  compact = false,
}: DocumentLifecycleTimelineProps) {
  // Fetch timeline data
  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['document-timeline', documentId],
    queryFn: () => lineageApi.getTimeline(documentId),
    enabled: !!documentId,
    staleTime: 2 * 60 * 1000, // Cache for 2 minutes
  });

  const events = data?.events || [];

  // Loading state
  if (isLoading) {
    return (
      <Card className={compact ? 'border-0 shadow-none' : ''}>
        <CardContent className="flex items-center justify-center py-12">
          <Loader2 className="h-6 w-6 animate-spin text-blue-600" />
        </CardContent>
      </Card>
    );
  }

  // Error state
  if (isError) {
    return (
      <Card className={compact ? 'border-0 shadow-none' : ''}>
        <CardContent className="flex flex-col items-center justify-center py-12 text-red-600">
          <AlertCircle className="h-6 w-6 mb-2" />
          <p className="text-sm">Failed to load timeline</p>
          <p className="text-xs text-muted-foreground mt-1">
            {(error as Error)?.message || 'Unknown error'}
          </p>
        </CardContent>
      </Card>
    );
  }

  // Empty state
  if (events.length === 0) {
    return (
      <Card className={compact ? 'border-0 shadow-none' : ''}>
        {!compact && (
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Clock className="h-4 w-4" />
              Document Timeline
            </CardTitle>
          </CardHeader>
        )}
        <CardContent className={compact ? 'py-4' : ''}>
          <div className="text-center py-8 text-muted-foreground">
            <Clock className="h-10 w-10 mx-auto mb-3 opacity-50" />
            <p className="text-sm">No timeline events recorded</p>
            <p className="text-xs mt-1">Events will appear as the document is processed</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className={compact ? 'border-0 shadow-none' : ''}>
      {!compact && (
        <CardHeader className="pb-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <Clock className="h-4 w-4 text-blue-600" />
            Document Timeline
          </CardTitle>
          <CardDescription className="text-xs">
            {events.length} event{events.length !== 1 ? 's' : ''} in document lifecycle
            {documentName && ` for ${documentName}`}
          </CardDescription>
        </CardHeader>
      )}

      <CardContent className={compact ? 'py-2' : ''}>
        {/* Summary badges */}
        <div className="flex flex-wrap gap-2 mb-4">
          {events.some(e => e.type === 'generated') && (
            <Badge variant="outline" className="bg-violet-50 text-violet-700 border-violet-200 gap-1">
              <Sparkles className="h-3 w-3" />
              AI Generated
            </Badge>
          )}
          {events.some(e => e.type === 'indexed') && (
            <Badge variant="outline" className="bg-emerald-50 text-emerald-700 border-emerald-200 gap-1">
              <Database className="h-3 w-3" />
              RAG Indexed
            </Badge>
          )}
          {events.filter(e => e.type === 'used_as_source').length > 0 && (
            <Badge variant="outline" className="bg-amber-50 text-amber-700 border-amber-200 gap-1">
              <GitBranch className="h-3 w-3" />
              {events.filter(e => e.type === 'used_as_source').length} derived doc(s)
            </Badge>
          )}
        </div>

        {/* Timeline */}
        <ScrollArea className={compact ? 'h-[250px]' : 'h-[350px]'}>
          <div className="space-y-0">
            {events.map((event, index) => (
              <TimelineEventItem
                key={`${event.type}-${event.timestamp}-${index}`}
                event={event}
                isLast={index === events.length - 1}
              />
            ))}
          </div>
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
