/**
 * Agent Badge Component
 *
 * Displays which AI agent generated a document section
 */

import { Bot, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface AgentMetadata {
  agent: string;
  method: 'specialized_agent' | 'generic_generation';
  agent_info?: {
    has_specialized_agent?: boolean;
    agent_name?: string;
  };
}

interface AgentBadgeProps {
  metadata?: AgentMetadata;
  compact?: boolean;
}

export function AgentBadge({ metadata, compact = false }: AgentBadgeProps) {
  if (!metadata) {
    return null;
  }

  const isSpecialized = metadata.method === 'specialized_agent';
  const agentName = metadata.agent
    ? metadata.agent.replace(/Agent$/, '').replace(/([A-Z])/g, ' $1').trim()
    : 'Unknown Agent';

  if (compact) {
    return (
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            {isSpecialized ? (
              <Sparkles className="h-4 w-4 text-blue-500" />
            ) : (
              <Bot className="h-4 w-4 text-slate-400" />
            )}
          </TooltipTrigger>
          <TooltipContent>
            <p className="text-xs">
              {isSpecialized ? `Generated by ${agentName}` : 'Generated by Claude (Generic)'}
            </p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    );
  }

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Badge
            variant={isSpecialized ? "default" : "secondary"}
            className={`text-xs ${
              isSpecialized
                ? 'bg-blue-100 text-blue-700 border-blue-300'
                : 'bg-slate-100 text-slate-600 border-slate-300'
            }`}
          >
            {isSpecialized ? (
              <>
                <Sparkles className="h-3 w-3 mr-1" />
                Specialized
              </>
            ) : (
              <>
                <Bot className="h-3 w-3 mr-1" />
                Generic
              </>
            )}
          </Badge>
        </TooltipTrigger>
        <TooltipContent side="top" className="max-w-xs">
          <div className="text-xs space-y-1">
            {isSpecialized ? (
              <>
                <p className="font-semibold">Specialized Agent</p>
                <p className="text-muted-foreground">{agentName}</p>
                <p className="text-muted-foreground mt-1">
                  This document was generated using a specialized agent trained specifically for this document type.
                </p>
              </>
            ) : (
              <>
                <p className="font-semibold">Generic Claude</p>
                <p className="text-muted-foreground">
                  This document was generated using the generic Claude AI model.
                </p>
              </>
            )}
          </div>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}

/**
 * Agent Stats Component
 * Shows overall statistics about specialized vs generic generation
 */
interface AgentStatsProps {
  agentMetadata?: Record<string, AgentMetadata>;
}

export function AgentStats({ agentMetadata }: AgentStatsProps) {
  if (!agentMetadata) {
    return null;
  }

  const total = Object.keys(agentMetadata).length;
  const specialized = Object.values(agentMetadata).filter(
    m => m.method === 'specialized_agent'
  ).length;
  const generic = total - specialized;
  const specializedPercent = total > 0 ? Math.round((specialized / total) * 100) : 0;

  if (total === 0) {
    return null;
  }

  return (
    <div className="flex items-center gap-4 text-sm">
      <div className="flex items-center gap-2">
        <Sparkles className="h-4 w-4 text-blue-500" />
        <span className="text-muted-foreground">
          {specialized} specialized agent{specialized !== 1 ? 's' : ''}
        </span>
      </div>
      {generic > 0 && (
        <div className="flex items-center gap-2">
          <Bot className="h-4 w-4 text-slate-400" />
          <span className="text-muted-foreground">
            {generic} generic
          </span>
        </div>
      )}
      {specializedPercent > 0 && (
        <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
          {specializedPercent}% specialized
        </Badge>
      )}
    </div>
  );
}
