/**
 * Feedback Buttons Component
 *
 * Allows users to rate AI-generated content with thumbs up/down
 * and optionally add comments. Used in the LiveEditor after each
 * generated section.
 *
 * Features:
 * - Thumbs up/down buttons for quick rating
 * - Optional comment input
 * - Shows existing feedback if already rated
 * - Toast notifications on submit
 */

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { ThumbsUp, ThumbsDown, MessageSquare, Check, Loader2, Bot } from 'lucide-react';
import { feedbackApi } from '@/services/api';
import { toast } from 'sonner';

interface FeedbackButtonsProps {
  documentId: string;
  sectionName?: string;
  agentName: string;
  existingFeedback?: { rating: string; comment?: string };
}

export function FeedbackButtons({
  documentId,
  sectionName,
  agentName,
  existingFeedback
}: FeedbackButtonsProps) {
  const [rating, setRating] = useState<string | null>(existingFeedback?.rating || null);
  const [showComment, setShowComment] = useState(false);
  const [comment, setComment] = useState(existingFeedback?.comment || '');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleRating = async (newRating: 'positive' | 'negative') => {
    // Don't submit if same rating already selected
    if (rating === newRating) return;

    setIsSubmitting(true);
    try {
      await feedbackApi.submit({
        document_id: documentId,
        section_name: sectionName,
        agent_name: agentName,
        rating: newRating,
        comment: comment || undefined
      });
      setRating(newRating);
      toast.success('Thanks for your feedback!');
    } catch (error) {
      console.error('Failed to submit feedback:', error);
      toast.error('Failed to submit feedback');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCommentSubmit = async () => {
    if (!comment.trim()) {
      toast.error('Please enter a comment');
      return;
    }

    if (!rating) {
      // If no rating yet, require them to rate first
      toast.error('Please rate the content first');
      return;
    }

    setIsSubmitting(true);
    try {
      await feedbackApi.submit({
        document_id: documentId,
        section_name: sectionName,
        agent_name: agentName,
        rating: rating as 'positive' | 'negative',
        comment: comment.trim()
      });
      setShowComment(false);
      toast.success('Comment added!');
    } catch (error) {
      console.error('Failed to submit comment:', error);
      toast.error('Failed to submit comment');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Format agent name for display (remove "Agent" suffix, add spaces before capitals)
  const displayAgentName = agentName
    .replace(/Agent$/, '')
    .replace(/([A-Z])/g, ' $1')
    .trim();

  return (
    <div className="border-t border-slate-200 mt-4 pt-3">
      {/* Agent attribution */}
      <div className="flex items-center gap-1.5 text-xs text-slate-500 mb-2">
        <Bot className="h-3.5 w-3.5" />
        <span>Generated by {displayAgentName}</span>
      </div>

      {/* Rating buttons row */}
      <div className="flex items-center gap-2 flex-wrap">
        <span className="text-xs text-slate-600">Was this helpful?</span>

        <Button
          variant={rating === 'positive' ? 'default' : 'ghost'}
          size="sm"
          onClick={() => handleRating('positive')}
          disabled={isSubmitting}
          className={`h-7 px-2 gap-1 ${
            rating === 'positive'
              ? 'bg-green-600 hover:bg-green-700 text-white'
              : 'hover:bg-green-50 hover:text-green-700'
          }`}
        >
          {isSubmitting && rating !== 'positive' ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <ThumbsUp className="h-3.5 w-3.5" />
          )}
          {rating === 'positive' && <Check className="h-3 w-3" />}
        </Button>

        <Button
          variant={rating === 'negative' ? 'destructive' : 'ghost'}
          size="sm"
          onClick={() => handleRating('negative')}
          disabled={isSubmitting}
          className={`h-7 px-2 gap-1 ${
            rating === 'negative'
              ? ''
              : 'hover:bg-red-50 hover:text-red-700'
          }`}
        >
          {isSubmitting && rating !== 'negative' ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <ThumbsDown className="h-3.5 w-3.5" />
          )}
          {rating === 'negative' && <Check className="h-3 w-3" />}
        </Button>

        <Button
          variant="ghost"
          size="sm"
          onClick={() => setShowComment(!showComment)}
          className="h-7 px-2 gap-1 text-slate-600 hover:text-slate-900"
        >
          <MessageSquare className="h-3.5 w-3.5" />
          <span className="text-xs">Add feedback</span>
        </Button>
      </div>

      {/* Comment input (collapsible) */}
      {showComment && (
        <div className="mt-3 space-y-2">
          <Textarea
            value={comment}
            onChange={(e) => setComment(e.target.value)}
            placeholder="Tell us more about your experience with this generated content..."
            className="text-sm min-h-[60px] resize-none"
            rows={2}
          />
          <div className="flex justify-end gap-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setShowComment(false)}
              disabled={isSubmitting}
            >
              Cancel
            </Button>
            <Button
              size="sm"
              onClick={handleCommentSubmit}
              disabled={isSubmitting || !comment.trim()}
            >
              {isSubmitting ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin mr-1" />
              ) : null}
              Submit
            </Button>
          </div>
        </div>
      )}

      {/* Show existing comment if any */}
      {existingFeedback?.comment && !showComment && (
        <div className="mt-2 text-xs text-slate-500 italic">
          "{existingFeedback.comment}"
        </div>
      )}
    </div>
  );
}
