"""
Document management models for checklist and file uploads
"""
from sqlalchemy import Column, String, DateTime, Date, Enum, Integer, BigInteger, ForeignKey, Boolean, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import uuid
import enum

from backend.database.base import Base
from backend.models.procurement import ProjectType, PhaseName


class DocumentStatus(str, enum.Enum):
    PENDING = "pending"
    UPLOADED = "uploaded"
    UNDER_REVIEW = "under_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXPIRED = "expired"


class ApprovalStatus(str, enum.Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    REQUESTED_CHANGES = "requested_changes"


class ApprovalRouting(str, enum.Enum):
    """
    Enum for document approval routing types.
    
    - MANUAL: User manually selects approvers from a list
    - AUTO_CO: Automatically route to project's assigned Contracting Officer
    - DEFAULT: Route to document's configured default approver
    """
    MANUAL = "manual"
    AUTO_CO = "auto_co"
    DEFAULT = "default"


class GenerationStatus(str, enum.Enum):
    """
    Enum for AI document generation status.
    
    - NOT_GENERATED: Document has not been generated by AI
    - GENERATING: AI generation is in progress
    - GENERATED: AI has successfully generated content
    - FAILED: AI generation failed
    """
    NOT_GENERATED = "NOT_GENERATED"
    GENERATING = "GENERATING"
    GENERATED = "GENERATED"
    FAILED = "FAILED"


class DocumentChecklistTemplate(Base):
    __tablename__ = "document_checklist_templates"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    contract_type = Column(Enum(ProjectType), nullable=False)
    document_name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    category = Column(String, default="General")
    phase = Column(Enum(PhaseName), nullable=True)
    is_required = Column(Boolean, default=True)
    typical_deadline_days = Column(Integer, nullable=True)
    requires_approval = Column(Boolean, default=False)
    display_order = Column(Integer, default=0)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    def to_dict(self):
        return {
            "id": str(self.id),
            "contract_type": self.contract_type.value,
            "document_name": self.document_name,
            "description": self.description,
            "category": self.category,
            "phase": self.phase.value if self.phase else None,
            "is_required": self.is_required,
            "typical_deadline_days": self.typical_deadline_days,
            "requires_approval": self.requires_approval,
            "display_order": self.display_order,
        }


class ProjectDocument(Base):
    __tablename__ = "project_documents"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("procurement_projects.id", ondelete="CASCADE"), nullable=False)
    document_name = Column(String, nullable=False)
    description = Column(Text, nullable=True)
    category = Column(String, default="General")
    phase = Column(Enum(PhaseName), nullable=True)
    is_required = Column(Boolean, default=True)
    status = Column(Enum(DocumentStatus), default=DocumentStatus.PENDING)
    deadline = Column(Date, nullable=True)
    expiration_date = Column(Date, nullable=True)
    requires_approval = Column(Boolean, default=False)
    assigned_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    notes = Column(Text, nullable=True)
    display_order = Column(Integer, default=0)
    
    # Smart approval routing fields
    # approval_routing: Determines how approval requests are routed (manual, auto_co, default)
    approval_routing = Column(Enum(ApprovalRouting), default=ApprovalRouting.AUTO_CO)
    # default_approver_id: User ID for default approver when routing is set to 'default'
    default_approver_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    
    # AI Generation fields
    # generation_status: Current status of AI content generation
    generation_status = Column(Enum(GenerationStatus), default=GenerationStatus.NOT_GENERATED)
    # generated_content: AI-generated markdown content for this document
    generated_content = Column(Text, nullable=True)
    # generated_at: Timestamp when content was generated
    generated_at = Column(DateTime(timezone=True), nullable=True)
    # generation_task_id: Task ID for tracking async generation
    generation_task_id = Column(String, nullable=True)
    # ai_quality_score: Quality score from AI generation (0-100)
    ai_quality_score = Column(Integer, nullable=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    project = relationship("ProcurementProject", back_populates="documents")
    uploads = relationship("DocumentUpload", back_populates="document", cascade="all, delete-orphan")
    approvals = relationship("DocumentApproval", back_populates="document", cascade="all, delete-orphan")
    # Relationship to default approver user (for DEFAULT routing)
    default_approver = relationship("User", foreign_keys=[default_approver_id])

    def to_dict(self):
        return {
            "id": str(self.id),
            "project_id": str(self.project_id),
            "document_name": self.document_name,
            "description": self.description,
            "category": self.category,
            "phase": self.phase.value if self.phase else None,
            "is_required": self.is_required,
            "status": self.status.value,
            "deadline": self.deadline.isoformat() if self.deadline else None,
            "expiration_date": self.expiration_date.isoformat() if self.expiration_date else None,
            "requires_approval": self.requires_approval,
            "assigned_user_id": str(self.assigned_user_id) if self.assigned_user_id else None,
            "notes": self.notes,
            "display_order": self.display_order,
            # Smart approval routing fields
            "approval_routing": self.approval_routing.value if self.approval_routing else "auto_co",
            "default_approver_id": str(self.default_approver_id) if self.default_approver_id else None,
            # AI generation fields
            "generation_status": self.generation_status.value.lower() if self.generation_status else "not_generated",
            "generated_content": self.generated_content,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "generation_task_id": self.generation_task_id,
            "ai_quality_score": self.ai_quality_score,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class DocumentUpload(Base):
    __tablename__ = "document_uploads"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_document_id = Column(UUID(as_uuid=True), ForeignKey("project_documents.id", ondelete="CASCADE"), nullable=False)
    file_name = Column(String, nullable=False)
    file_path = Column(String, nullable=False)
    file_size = Column(BigInteger, nullable=False)
    file_type = Column(String, nullable=False)
    version_number = Column(Integer, default=1)
    uploaded_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    upload_date = Column(DateTime(timezone=True), server_default=func.now())
    is_current_version = Column(Boolean, default=True)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    document = relationship("ProjectDocument", back_populates="uploads")
    approvals = relationship("DocumentApproval", back_populates="upload")

    def to_dict(self):
        return {
            "id": str(self.id),
            "project_document_id": str(self.project_document_id),
            "file_name": self.file_name,
            "file_path": self.file_path,
            "file_size": self.file_size,
            "file_type": self.file_type,
            "version_number": self.version_number,
            "uploaded_by": str(self.uploaded_by),
            "upload_date": self.upload_date.isoformat() if self.upload_date else None,
            "is_current_version": self.is_current_version,
            "notes": self.notes,
        }


class DocumentApproval(Base):
    __tablename__ = "document_approvals"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_document_id = Column(UUID(as_uuid=True), ForeignKey("project_documents.id", ondelete="CASCADE"), nullable=False)
    document_upload_id = Column(UUID(as_uuid=True), ForeignKey("document_uploads.id", ondelete="SET NULL"), nullable=True)
    approver_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    delegated_from_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)  # Original approver if delegated
    approval_status = Column(Enum(ApprovalStatus), default=ApprovalStatus.PENDING)
    approval_date = Column(DateTime(timezone=True), nullable=True)
    comments = Column(Text, nullable=True)
    requested_at = Column(DateTime(timezone=True), server_default=func.now())
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    document = relationship("ProjectDocument", back_populates="approvals")
    upload = relationship("DocumentUpload", back_populates="approvals")

    def to_dict(self):
        return {
            "id": str(self.id),
            "project_document_id": str(self.project_document_id),
            "document_upload_id": str(self.document_upload_id) if self.document_upload_id else None,
            "approver_id": str(self.approver_id),
            "delegated_from_id": str(self.delegated_from_id) if self.delegated_from_id else None,
            "approval_status": self.approval_status.value,
            "approval_date": self.approval_date.isoformat() if self.approval_date else None,
            "comments": self.comments,
            "requested_at": self.requested_at.isoformat() if self.requested_at else None,
        }


class ApprovalAuditLog(Base):
    __tablename__ = "approval_audit_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    approval_id = Column(UUID(as_uuid=True), ForeignKey("document_approvals.id", ondelete="CASCADE"), nullable=False)
    action = Column(String, nullable=False)  # requested, approved, rejected, delegated, requested_changes
    performed_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    details = Column(Text, nullable=True)  # JSON or text details about the action
    timestamp = Column(DateTime(timezone=True), server_default=func.now())

    def to_dict(self):
        return {
            "id": str(self.id),
            "approval_id": str(self.approval_id),
            "action": self.action,
            "performed_by": str(self.performed_by),
            "details": self.details,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
        }
